name: streamgit-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - streamlit=1.25.0
  - pandas=1.5.3
  - pygithub=1.55
  - plotly=5.15.0
  - python-dotenv=1.0.0
  - python-kaleido=0.2.1
  - pip
  - freezegun=1.2.0
  - openpyxl=3.1.2
  - pip:
      - streamlit-option-menu==0.3.2