name: streamgit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - streamlit
  - pandas
  - pygithub
  - plotly
  - python-dotenv
  - python-kaleido
  - pip
  - pip:
    - streamlit-option-menu